<!DOCTYPE html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?php echo $title; ?> - <?php echo $nome_empresa; ?></title><base href="<?php echo $url; ?>"><meta name="description" content="<?php echo $description; ?>"><meta name="keywords" content="<?php echo $keywords; ?>"><meta name="ICBM" content="<?php echo $unidades[1]["latitude_longitude"]; ?>"><meta name="robots" content="index,follow"><meta name="rating" content="General"><meta name="revisit-after" content="7 days"><meta name="author" content="<?php echo $nome_empresa; ?>"><link rel="canonical" href="<?php echo $canonical; ?>"><link rel="shortcut icon" href="<?php echo $url; ?>imagens/favicon.png"><meta property="og:locale" content="pt_BR"><meta property="og:region" content="Brasil"><meta property="og:title" content="<?php echo $title; ?>"><?php echo !empty($meta_img)?"<meta property=\"og:image\" content=\"".$meta_img."\">":""; ?><meta property="og:url" content="<?php echo $canonical; ?>"><meta property="og:description" content="<?php echo $description; ?>"><meta property="og:site_name" content="<?php echo $nome_empresa; ?>"><meta property="og:type" content="website"><meta name="geo.position" content="<?php echo $unidades[1]["latitude_longitude"]; ?>"><meta name="geo.placename" content="<?php echo $unidades[1]["estado"]; ?>-<?php echo $unidades[1]["uf"]; ?>"><meta name="geo.region" content="<?php echo $unidades[1]["uf"]; ?>-BR"><meta name="twitter:card" content="summary"><meta name="twitter:url" content="<?php echo $canonical; ?>"><meta name="twitter:title" content="<?php echo $title; ?>"><meta name="twitter:description" content="<?php echo $description; ?>"><link rel="preload" href="<?php echo $url; ?>imagens/main/slide-home/1.webp" as="image" type="image/webp" fetchpriority="high"><link rel="preload" href="<?php echo $url; ?>imagens/main/slide-home/1mob.webp" as="image" type="image/webp" fetchpriority="high"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Raleway:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Raleway:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" media="print" onload="this.media='all'"> <link rel="preload" href="https://kit.fontawesome.com/76cc86e992.js" as="script" crossorigin="anonymous"><script src="https://kit.fontawesome.com/76cc86e992.js" crossorigin="anonymous" defer></script><?php echo !empty($meta_img)?"<meta name=\"twitter:image\" content=\"".$meta_img."\">":"";
$retorno = '<script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"'.$nome_empresa.'","image":"'.$url.$logo_cliente.'","telephone":[';
foreach ($telefones_cliente as $key => $tel) {$retorno .= '"' . $tel . '"' . (($key + 1) < count($telefones_cliente) ? ',': '');}
$retorno .='],"email":"'.$emailContato.'","address":{"@type":"PostalAddress","streetAddress":"'.$unidades[1]['rua'].'","addressLocality":"'.$unidades[1]['bairro'].'","addressRegion":"'.$unidades[1]['cidade'].'","postalCode":"'.$unidades[1]['cep'].'"},"url":"'.$url.'"}</script>';
$retorno .= '<script type="application/ld+json">{"@context":"https://schema.org","@type":"WebPage","name":"'.$title.'","description":"'.addslashes($description).'","url":"'.$canonical.'","datePublished":"'.$dataDePublicacao.'","dateModified":"'.$dataDeModificacao.'","image":"'.(!empty($meta_img) ? $meta_img : $url.$logo_cliente).'","publisher":{"@type":"Organization","name":"'.$nome_empresa.'","logo":{"@type":"ImageObject","name":"'.$nome_empresa.'","url":"'.$url.$logo_cliente.'"}},"mainEntityOfPage":{"@type":"WebPage","@id":"'.$canonical.'"}}</script>';
$retorno .= '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"'.$nome_empresa.'","url":"'.$url.'","logo":{"@type":"ImageObject","name":"'.$nome_empresa.'","url":"'.$url.$logo_cliente.'"},"contactPoint":[';
foreach ($telefones_cliente as $key => $tel) {$retorno .='{"@type":"ContactPoint","telephone":"+55 '.$tel.'","contactType":"customer service"}' . (($key + 1) < count($telefones_cliente) ? ',': '');}
$retorno .='],"sameAs":["https://www.facebook.com/'.$facebook.'/","https://www.instagram.com/'.$instagram.'/","https://www.linkedin.com/company/'.$linkedin.'/","https://www.youtube.com/@'.$youtube.'"]}</script>';
$paginaTratada = "";if ($canonical != $url) {$paginaTratada .= '/';} else {$paginaTratada .= '';}$paginaTratada .= str_replace($url, '', $canonical);
$retorno .= '<script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[';$pg = explode('/', $paginaTratada);$breadcrumbjs = '';$arvore = '';foreach ($pg as $key => $value) {$arvore .= $value;$breadcrumbjs .= '{"@type":"ListItem","position":'.($key + 1).',"name":"'.$title.'","item":"'.$url.$arvore.'"},';}$breadcrumbjs = $borg->replace($breadcrumbjs, '},', 0, '}');$retorno .= $breadcrumbjs;$retorno .= ']}</script>';
echo str_replace(array("\t"), '', $retorno);?><?php echo $direitosAutorais; ?>
