<?php
    $servicos = [
'regularizacao-empresarial' => [
    'name' => 'regularizacao-empresarial',
    'title' => 'Regularização Empresarial',
    'title2' => '<h2>Regularização Empresarial: Segurança Jurídica e Fiscal para sua Empresa</h2>',
    'desc' => '<p>A regularização empresarial é essencial para garantir que sua empresa opere em conformidade com as normas legais e evite problemas fiscais e jurídicos. Oferecemos assessoria completa para abertura, alteração e encerramento de empresas, assegurando a conformidade com os órgãos públicos e mantendo sua empresa em dia com as exigências legais.</p>',
    'icon1' => '<i class="fa-solid fa-building-circle-check"></i>',
    'icon2' => '<i class="fa-solid fa-file-circle-check"></i>',
    'icon3' => '<i class="fa-solid fa-file-pen"></i>',
    'icon4' => '<i class="fa-solid fa-shield-halved"></i>',
    'icon-title1' => '<h2>Legalização Completa</h2>',
    'icon-title2' => '<h2>Conformidade com Órgãos Públicos</h2>',
    'icon-title3' => '<h2>Gestão de Débitos Fiscais </h2>',
    'icon-title4' => '<h2>Segurança Fiscal</h2>',
    'desc-icon1' => '<p>Cuidamos de todo o processo de abertura, alteração e encerramento da sua empresa, com agilidade e segurança.</p>',
    'desc-icon2' => '<p>Garantimos que sua empresa esteja regular perante Receita Federal, Prefeitura, Estado e demais entidades reguladoras.</p>',
    'desc-icon3' => '<p>Negociação e parcelamento de débitos fiscais da empresa conforme mudanças societárias ou operacionais.</p>',
    'desc-icon4' => '<p>Evite riscos legais com uma empresa regularizada e em conformidade com todas as exigências legais.</p>',
],
'recursos-humanos' => [
    'name' => 'recursos-humanos',
    'title' => 'Recursos Humanos',
    'title2' => '<h2>Recursos Humanos: Gestão Estratégica de Talentos</h2>',
    'desc' => '<p>O setor de Recursos Humanos é essencial para atrair, desenvolver e reter talentos que impulsionam o crescimento da sua empresa. Oferecemos soluções completas em gestão de pessoas, desde o recrutamento até o desenvolvimento de lideranças, promovendo um ambiente de trabalho mais saudável, eficiente e produtivo.</p>',
    'icon1' => '<i class="fa-solid fa-magnifying-glass"></i>',
    'icon2' => '<i class="fa-solid fa-chalkboard-user"></i>',
    'icon3' => '<i class="fa-solid fa-ranking-star"></i>',
    'icon4' => '<i class="fa-solid fa-people-group"></i>',
    'icon-title1' => '<h2>Recrutamento e Seleção</h2>',
    'icon-title2' => '<h2>Treinamento e Desenvolvimento</h2>',
    'icon-title3' => '<h2>Avaliação de Desempenho</h2>',
    'icon-title4' => '<h2>Retenção de Talentos</h2>',
    'desc-icon1' => '<p>Identificamos e atraímos os melhores profissionais para integrar sua equipe de forma estratégica.</p>',
    'desc-icon2' => '<p>Capacitamos seus colaboradores para melhor desempenho e crescimento contínuo dentro da empresa.</p>',
    'desc-icon3' => '<p>Implementamos ferramentas de avaliação para mensurar a performance individual e coletiva de sua equipe.</p>',
    'desc-icon4' => '<p>Desenvolvemos políticas eficazes para manter seus melhores talentos engajados e comprometidos.</p>',
],
      'departamento-pessoal' => [
        'name' => 'departamento-pessoal',
        'title' => 'Departamento Pessoal',
        'title2' => '<h2>Departamento Pessoal: Gestão Estratégica de Pessoas</h2>',
        'desc' => '<p>O Departamento Pessoal é essencial para a administração correta dos funcionários, cumprimento das obrigações trabalhistas e a garantia de um ambiente organizacional produtivo e seguro. Nossa equipe especializada auxilia sua empresa desde a admissão até o desligamento de colaboradores, garantindo conformidade legal e processos ágeis.</p>',
        'icon1' => '<i class="fa-solid fa-users"></i>',
        'icon2' => '<i class="fa-solid fa-user-plus"></i>',
        'icon3' => '<i class="fa-solid fa-file-signature"></i>',
        'icon4' => '<i class="fa-solid fa-scale-balanced"></i>',
        'icon-title1' => '<h2>Gestão de Folha de Pagamento</h2>',
        'icon-title2' => '<h2>Admissão e Demissão de Funcionários</h2>',
        'icon-title3' => '<h2>Gestão de Benefícios</h2>',
        'icon-title4' => '<h2>Conformidade Trabalhista</h2>',
        'desc-icon1' => '<p>Elaboração e controle da folha de pagamento, garantindo cálculos precisos de salários, encargos trabalhistas e benefícios.</p>',
        'desc-icon2' => '<p>Processos completos de contratação e desligamento de colaboradores, assegurando conformidade com a legislação trabalhista e previdenciária.</p>',
        'desc-icon3' => '<p>Administração de benefícios como vale-transporte, vale-refeição, planos de saúde e previdência privada, otimizando custos para a empresa e colaboradores.</p>',
        'desc-icon4' => '<p>Garantimos que sua empresa esteja em conformidade com as normas da CLT, Sindical, eSocial e demais exigências legais, evitando penalidades.</p>',
      ],
'treinamento-personalizado' => [
    'name' => 'treinamento-personalizado',
    'title' => 'Treinamento Personalizado',
    'title2' => '<h2>Treinamento Personalizado: Desenvolvimento Profissional Sob Medida</h2>',
    'desc' => '<p>Oferecemos programas de treinamento personalizados para atender às necessidades específicas da sua equipe. Nossos treinamentos são desenvolvidos com base na realidade do seu negócio, promovendo aprendizado prático, motivação e aumento de desempenho individual e coletivo.</p>',
    'icon1' => '<i class="fa-solid fa-bullseye"></i>',
    'icon2' => '<i class="fa-solid fa-laptop"></i>',
    'icon3' => '<i class="fa-solid fa-chart-line"></i>',
    'icon4' => '<i class="fa-solid fa-people-arrows"></i>',
    'icon-title1' => '<h2>Treinamentos Sob Medida</h2>',
    'icon-title2' => '<h2>Modalidades Flexíveis</h2>',
    'icon-title3' => '<h2>Acompanhamento de Resultados</h2>',
    'icon-title4' => '<h2>Desenvolvimento de Equipes</h2>',
    'desc-icon1' => '<p>Criamos conteúdos adaptados à realidade e aos desafios específicos do seu time e setor.</p>',
    'desc-icon2' => '<p>Capacitações presenciais ou à distância, com recursos modernos e metodologias ativas de ensino.</p>',
    'desc-icon3' => '<p>Mensuramos o impacto do treinamento no desempenho dos colaboradores com avaliações práticas.</p>',
    'desc-icon4' => '<p>Fortalecemos o trabalho em equipe, a comunicação e a liderança, promovendo maior integração entre os colaboradores.</p>',
],
'bpo-financeiro' => [
    'name' => 'bpo-financeiro',
    'title' => 'BPO Financeiro',
    'title2' => '<h2>BPO Financeiro: Terceirização Inteligente da Gestão Financeira</h2>',
    'desc' => '<p>O BPO Financeiro é a solução ideal para empresas que desejam focar em seu core business enquanto garantem uma gestão financeira precisa, segura e estratégica. Assumimos toda a rotina financeira do seu negócio com profissionais especializados e processos otimizados.</p>',
    'icon1' => '<i class="fa-solid fa-cash-register"></i>',
    'icon2' => '<i class="fa-solid fa-file-invoice-dollar"></i>',
    'icon3' => '<i class="fa-solid fa-lock"></i>',
    'icon4' => '<i class="fa-solid fa-business-time"></i>',
    'icon-title1' => '<h2>Controle Financeiro Eficiente</h2>',
    'icon-title2' => '<h2>Relatórios Gerenciais</h2>',
    'icon-title3' => '<h2>Segurança e Confidencialidade</h2>',
    'icon-title4' => '<h2>Mais Tempo para o Core Business</h2>',
    'desc-icon1' => '<p>Contas a Pagar e Receber, Conciliação bancárias, faturamento e estratégias para fluxo de caixa.</p>',
    'desc-icon2' => '<p>Informações claras e organizadas para apoiar a tomada de decisão estratégica com base em dados reais.</p>',
    'desc-icon3' => '<p>Garantia de sigilo e integridade nas informações financeiras da empresa, com sistemas seguros.</p>',
    'desc-icon4' => '<p>Ao terceirizar o financeiro, você dedica mais tempo à estratégia e crescimento da empresa.</p>',
],
'assessoria-em-investimentos-e-financiamentos' => [
    'name' => 'assessoria-em-investimentos-e-financiamentos',
    'title' => 'Assessoria em Investimentos e Financiamentos',
    'title2' => '<h2>Assessoria em Investimentos e Financiamentos: Apoio Estratégico para Decisões Financeiras</h2>',
    'desc' => '<p>Nossa assessoria em investimentos e financiamentos é voltada para empresas que buscam crescimento sustentável, acesso a crédito estratégico e aplicação eficiente de recursos. Analisamos o perfil do seu negócio e oferecemos as melhores opções disponíveis no mercado.</p>',
    'icon1' => '<i class="fa-solid fa-hand-holding-dollar"></i>',
    'icon2' => '<i class="fa-solid fa-piggy-bank"></i>',
    'icon3' => '<i class="fa-solid fa-chart-line"></i>',
    'icon4' => '<i class="fa-solid fa-building-columns"></i>',
    'icon-title1' => '<h2>Planejamento de Investimentos</h2>',
    'icon-title2' => '<h2>Consultoria em Crédito</h2>',
    'icon-title3' => '<h2>Viabilidade Econômica</h2>',
    'icon-title4' => '<h2>Negociação com Instituições</h2>',
    'desc-icon1' => '<p>Identificação de oportunidades e construção de estratégias que maximizam o retorno financeiro com segurança.</p>',
    'desc-icon2' => '<p>Orientação na escolha da melhor linha de crédito com base nas taxas, prazos e necessidades da empresa.</p>',
    'desc-icon3' => '<p>Análise detalhada dos impactos financeiros de cada projeto ou operação, garantindo decisões mais assertivas.</p>',
    'desc-icon4' => '<p>Intermediação junto a bancos e agentes financeiros para garantir as melhores condições contratuais.</p>',
],
'gestao-de-riscos-e-controles-internos' => [
    'name' => 'gestao-de-riscos-e-controles-internos',
    'title' => 'Gestão de Riscos e Controles Internos',
    'title2' => '<h2>Gestão de Riscos e Controles Internos: Segurança e Confiabilidade para sua Empresa</h2>',
    'desc' => '<p>Oferecemos soluções eficazes para identificar, avaliar e mitigar riscos operacionais, financeiros e regulatórios. Implementamos controles internos que fortalecem a governança corporativa, promovem a transparência e protegem os ativos da empresa.</p>',
    'icon1' => '<i class="fa-solid fa-shield-halved"></i>',
    'icon2' => '<i class="fa-solid fa-clipboard-check"></i>',
    'icon3' => '<i class="fa-solid fa-magnifying-glass-chart"></i>',
    'icon4' => '<i class="fa-solid fa-chart-pie"></i>',
    'icon-title1' => '<h2>Mapeamento de Riscos</h2>',
    'icon-title2' => '<h2>Controles Internos</h2>',
    'icon-title3' => '<h2>Auditoria e Compliance</h2>',
    'icon-title4' => '<h2>Monitoramento Contínuo</h2>',
    'desc-icon1' => '<p>Identificação de riscos operacionais, financeiros e estratégicos, promovendo decisões mais seguras.</p>',
    'desc-icon2' => '<p>Criação e estruturação de processos que reduzem falhas, previnem fraudes e garantem eficiência operacional.</p>',
    'desc-icon3' => '<p>Apoio na adequação às normas e regulamentos, além de suporte em auditorias internas e externas.</p>',
    'desc-icon4' => '<p>Verificação periódica de controles e indicadores para antecipar problemas e garantir conformidade.</p>',
],
'reducao-de-custos' => [
    'name' => 'reducao-de-custos',
    'title' => 'Redução de Custo',
    'title2' => '<h2>Redução de Custo: Otimize Recursos e Aumente sua Lucratividade</h2>',
    'desc' => '<p>A Redução de Custo é uma estratégia essencial para empresas que desejam manter a competitividade e melhorar seus resultados financeiros. Atuamos na identificação de desperdícios, reestruturação de processos e renegociação de contratos, gerando economia sem comprometer a qualidade.</p>',
    'icon1' => '<i class="fa-solid fa-money-bill-trend-up"></i>',
    'icon2' => '<i class="fa-solid fa-handshake-angle"></i>',
    'icon3' => '<i class="fa-solid fa-recycle"></i>',
    'icon4' => '<i class="fa-solid fa-gauge-high"></i>',
    'icon-title1' => '<h2>Mapeamento de Despesas</h2>',
    'icon-title2' => '<h2>Renegociação de Contratos</h2>',
    'icon-title3' => '<h2>Eficiência Operacional</h2>',
    'icon-title4' => '<h2>Identificação de riscos fiscais;</h2>',
    'desc-icon1' => '<p>Análise detalhada dos custos operacionais para identificar oportunidades de economia.</p>',
    'desc-icon2' => '<p>Negociações mais vantajosas com fornecedores, reduzindo custos sem perder qualidade.</p>',
    'desc-icon3' => '<p>Melhoria de processos e uso racional de recursos para aumentar a produtividade com menos gastos.</p>',
    'desc-icon4' => '<p>Revisão nos regimes: Simples Nacional, Lucro Presumido ou Lucro Real. Auditoria conta de água, luz, telefone, entre outras.</p>',
],
'blindagem-de-patrimonio' => [
    'name' => 'blindagem-de-patrimonio',
    'title' => 'Blindagem de Patrimônio',
    'title2' => '<h2>Blindagem de Patrimônio: Proteja Seus Bens com Segurança Jurídica</h2>',
    'desc' => '<p>Blindar o patrimônio é essencial para empresários e investidores que desejam proteger seus bens pessoais contra riscos jurídicos e financeiros. Utilizamos estratégias legais e seguras para garantir a separação entre o patrimônio pessoal e o empresarial, evitando perdas desnecessárias.</p>',
    'icon1' => '<i class="fa-solid fa-shield-halved"></i>',
    'icon2' => '<i class="fa-solid fa-hand-holding-dollar"></i>',
    'icon3' => '<i class="fa-solid fa-building-lock"></i>',
    'icon4' => '<i class="fa-solid fa-file-contract"></i>',
    'icon-title1' => '<h2>Proteção de Bens Pessoais</h2>',
    'icon-title2' => '<h2>Planejamento Sucessório</h2>',
    'icon-title3' => '<h2>Criação de Holdings</h2>',
    'icon-title4' => '<h2>Gestão Jurídica Estratégica</h2>',
    'desc-icon1' => '<p>Separação patrimonial que impede a responsabilização pessoal por dívidas da empresa.</p>',
    'desc-icon2' => '<p>Organização da sucessão dos bens, evitando conflitos familiares e reduzindo tributos.</p>',
    'desc-icon3' => '<p>Estruturação de empresas para controle patrimonial com benefícios fiscais e proteção jurídica.</p>',
    'desc-icon4' => '<p>Consultoria especializada para evitar passivos judiciais e garantir segurança nos negócios.</p>',
],
'avaliacao-da-empresa' => [
    'name' => 'avaliacao-da-empresa',
    'title' => 'Avaliação da Empresa',
    'title2' => '<h2>Avaliação da Empresa: Conheça o Valor Real do seu Negócio</h2>',
    'desc' => '<p>Saber quanto vale sua empresa é essencial para decisões estratégicas como venda, fusão, aquisição ou captação de investimentos. Nossa consultoria realiza avaliações empresariais com métodos reconhecidos, fornecendo um retrato fiel do valor do seu negócio.</p>',
    'icon1' => '<i class="fa-solid fa-chart-line"></i>',
    'icon2' => '<i class="fa-solid fa-calculator"></i>',
    'icon3' => '<i class="fa-solid fa-lightbulb"></i>',
    'icon4' => '<i class="fa-solid fa-file-lines"></i>',
    'icon-title1' => '<h2>Valuation Estratégico</h2>',
    'icon-title2' => '<h2>Análise Financeira Profunda</h2>',
    'icon-title3' => '<h2>Identificação de Oportunidades</h2>',
    'icon-title4' => '<h2>Relatórios Completos</h2>',
    'desc-icon1' => '<p>Determinação do valor de mercado da empresa com base em dados concretos e projeções realistas.</p>',
    'desc-icon2' => '<p>Estudo minucioso das demonstrações contábeis e indicadores de desempenho financeiro.</p>',
    'desc-icon3' => '<p>Descoberta de pontos fortes, riscos e oportunidades de melhoria no desempenho da empresa.</p>',
    'desc-icon4' => '<p>Documentação técnica e estratégica para uso em negociações, auditorias ou planejamento futuro.</p>',
],
'solucao-de-conflitos-corporativos' => [
    'name' => 'solucao-de-conflitos-corporativos',
    'title' => 'Solução de Conflitos Corporativos',
    'title2' => '<h2>Solução de Conflitos Corporativos: Mediação Estratégica para o Sucesso do Negócio</h2>',
    'desc' => '<p>Conflitos dentro de empresas podem comprometer o desempenho, a cultura organizacional e até a continuidade do negócio. Atuamos de forma estratégica para identificar, mediar e resolver disputas entre sócios, gestores e colaboradores, preservando o valor da empresa e seus relacionamentos.</p>',
    'icon1' => '<i class="fa-solid fa-handshake-simple"></i>',
    'icon2' => '<i class="fa-solid fa-scale-balanced"></i>',
    'icon3' => '<i class="fa-solid fa-comments"></i>',
    'icon4' => '<i class="fa-solid fa-people-roof"></i>',
    'icon-title1' => '<h2>Mediação de Conflitos</h2>',
    'icon-title2' => '<h2>Consultoria</h2>',
    'icon-title3' => '<h2>Comunicação Estratégica</h2>',
    'icon-title4' => '<h2>Ambiente Organizacional Saudável</h2>',
    'desc-icon1' => '<p>Atuação imparcial para facilitar o diálogo e a construção de acordos entre as partes envolvidas.</p>',
    'desc-icon2' => '<p>Avaliação de contratos e acordos societários para prevenir e resolver disputas legais.</p>',
    'desc-icon3' => '<p>Fortalecimento do diálogo entre equipes e lideranças, reduzindo ruídos e mal-entendidos.</p>',
    'desc-icon4' => '<p>Criação de estratégias para promover confiança, respeito mútuo e cooperação entre os colaboradores.</p>',
],
'encerramento-de-empresas-com-diferencial-estrategico' => [
    'name' => 'encerramento-de-empresas-com-diferencial-estrategico',
    'title' => 'Encerramento de Empresas com Diferencial Estratégico',
    'title2' => '<h2>Encerramento Estratégico de Empresas: Planejamento, Agilidade e Conformidade</h2>',
    'desc' => '<p>O encerramento de uma empresa exige mais do que o simples cumprimento de formalidades legais. Nossa abordagem estratégica garante a finalização das atividades com segurança jurídica, mitigando riscos e protegendo o patrimônio dos sócios, enquanto evita passivos ocultos e problemas fiscais futuros.</p>',
    'icon1' => '<i class="fa-solid fa-clipboard-check"></i>',
    'icon2' => '<i class="fa-solid fa-gavel"></i>',
    'icon3' => '<i class="fa-solid fa-recycle"></i>',
    'icon4' => '<i class="fa-solid fa-user-shield"></i>',
    'icon-title1' => '<h2>Levantamento de Pendências</h2>',
    'icon-title2' => '<h2>Segurança Jurídica</h2>',
    'icon-title3' => '<h2>Reaproveitamento de Ativos</h2>',
    'icon-title4' => '<h2>Preservação da Imagem</h2>',
    'desc-icon1' => '<p>Mapeamento de todas as obrigações fiscais, contábeis e trabalhistas pendentes, garantindo regularização antes da baixa.</p>',
    'desc-icon2' => '<p>Encerramento com respaldo legal e acompanhamento por especialistas, protegendo os sócios e evitando autuações.</p>',
    'desc-icon3' => '<p>Planejamento para realocação de bens e recursos para novas iniciativas ou dissolução eficiente dos ativos da empresa.</p>',
    'desc-icon4' => '<p>Encerramento planejado e ético, que mantém a reputação da empresa no mercado e respeita seus compromissos legais e sociais.</p>',
],
'reestruturacao-empresarial' => [
    'name' => 'reestruturacao-empresarial',
    'title' => 'Reestruturação Empresarial',
    'title2' => '<h2>Reestruturação Empresarial: Transformando Desafios em Oportunidades</h2>',
    'desc' => '<p>A reestruturação empresarial é essencial para organizações que desejam superar crises, otimizar recursos ou preparar-se para novos ciclos de crescimento. Através de um diagnóstico detalhado, oferecemos soluções personalizadas para ajustar estrutura organizacional, processos e finanças, promovendo estabilidade e competitividade.</p>',
    'icon1' => '<i class="fa-solid fa-magnifying-glass-chart"></i>',
    'icon2' => '<i class="fa-solid fa-diagram-project"></i>',
    'icon3' => '<i class="fa-solid fa-handshake-angle"></i>',
    'icon4' => '<i class="fa-solid fa-chart-line"></i>',
    'icon-title1' => '<h2>Diagnóstico Empresarial</h2>',
    'icon-title2' => '<h2>Reorganização Estrutural</h2>',
    'icon-title3' => '<h2>Renegociação de Passivos</h2>',
    'icon-title4' => '<h2>Planejamento para Crescimento</h2>',
    'desc-icon1' => '<p>Mapeamento de processos, estrutura e finanças para identificar gargalos e oportunidades de melhoria.</p>',
    'desc-icon2' => '<p>Reformulação do organograma e processos internos para maior eficiência e agilidade operacional.</p>',
    'desc-icon3' => '<p>Negociação com credores e otimização do fluxo de caixa, preservando o capital de giro e a sustentabilidade do negócio.</p>',
    'desc-icon4' => '<p>Estratégias de curto, médio e longo prazo para garantir um novo ciclo de expansão com base sólida e controlada.</p>',
],
'negocios-empresariais' => [
    'name' => 'negocios-empresariais',
    'title' => 'Negócios Empresariais',
    'title2' => '<h2>Negócios Empresariais: Soluções Estratégicas para o Crescimento Sustentável</h2>',
    'desc' => '<p>Nosso serviço de Negócios Empresariais oferece suporte completo para a gestão estratégica, análise de oportunidades, estruturação de parcerias e expansão de mercado. Atuamos como aliados na tomada de decisões importantes, sempre com foco em resultados sólidos e sustentáveis.</p>',
    'icon1' => '<i class="fa-solid fa-lightbulb"></i>',
    'icon2' => '<i class="fa-solid fa-chart-pie"></i>',
    'icon3' => '<i class="fa-solid fa-file-contract"></i>',
    'icon4' => '<i class="fa-solid fa-handshake-simple"></i>',
    'icon-title1' => '<h2>Planejamento estratégico</h2>',
    'icon-title2' => '<h2>Análise de Viabilidade</h2>',
    'icon-title3' => '<h2>Estruturação Contratual</h2>',
    'icon-title4' => '<h2>Criação de redes e franquias</h2>',
    'desc-icon1' => '<p>Registro de marcas e patentes, venda ou revenda de produtos, compra e venda de empresa</p>',
    'desc-icon2' => '<p>Estudo detalhado sobre a viabilidade de novos empreendimentos, fusões e expansões com base em dados de mercado.</p>',
    'desc-icon3' => '<p>Redação e revisão de contratos comerciais, societários e de parceria com foco na proteção jurídica e eficiência empresarial.</p>',
    'desc-icon4' => '<p>Assessoria em parcerias estratégicas, joint ventures e alianças comerciais com foco em crescimento mútuo e escalabilidade.</p>',
],
// 'certificado-digital' => [
//     'name' => 'certificado-digital',
//     'title' => 'Certificado Digital',
//     'title2' => '<h2>Certificado Digital: Segurança e Agilidade nas Transações</h2>',
//     'desc' => '<p>O Certificado Digital é essencial para garantir autenticidade, confidencialidade e integridade em transações eletrônicas. Com ele, você pode assinar documentos digitalmente, acessar sistemas do governo e realizar processos fiscais com segurança jurídica.</p>',
//     'icon1' => '<i class="fa-solid fa-key"></i>',
//     'icon2' => '<i class="fa-solid fa-laptop-file"></i>',
//     'icon3' => '<i class="fa-solid fa-paper-plane"></i>',
//     'icon4' => '<i class="fa-solid fa-clock"></i>',
//     'icon-title1' => '<h2>Segurança Jurídica</h2>',
//     'icon-title2' => '<h2>Acesso a Sistemas Oficiais</h2>',
//     'icon-title3' => '<h2>Redução de Burocracia</h2>',
//     'icon-title4' => '<h2>Validade Imediata</h2>',
//     'desc-icon1' => '<p>Assinaturas com validade legal, dispensando reconhecimento de firma em cartório e garantindo integridade documental.</p>',
//     'desc-icon2' => '<p>Permite acesso a plataformas como Receita Federal, Caixa Econômica, eSocial, entre outras, com total segurança.</p>',
//     'desc-icon3' => '<p>Menos papelada, menos deslocamentos, mais eficiência. Automatize processos e otimize o tempo da sua equipe.</p>',
//     'desc-icon4' => '<p>Certificados emitidos de forma rápida, com validade imediata para utilização em diversos serviços digitais.</p>',
// ],
'contabil-fiscal' => [
    'name' => 'contabil-fiscal',
    'title' => 'Contábil / Fiscal',
    'title2' => '<h2>Contabilidade e Fiscal: Inteligência Tributária e Conformidade</h2>',
    'desc' => '<p>Oferecemos soluções contábeis e fiscais completas, adaptadas às necessidades de cada empresa, garantindo conformidade, otimização de processos e inteligência estratégica. Com uma abordagem consultiva e personalizada, transformamos dados contábeis e obrigações fiscais em instrumentos de gestão e crescimento sustentável.</p>',
    'icon1' => '<i class="fa-solid fa-scale-balanced"></i>',
    'icon2' => '<i class="fa-solid fa-file-invoice-dollar"></i>',
    'icon3' => '<i class="fa-solid fa-calculator"></i>',
    'icon4' => '<i class="fa-solid fa-chart-line"></i>',
    'icon-title1' => '<h2>Demonstrações Contábeis</h2>',
    'icon-title2' => '<h2>Planejamento Tributário</h2>',
    'icon-title3' => '<h2>Gestão Fiscal</h2>',
    'icon-title4' => '<h2>Otimização de Regimes</h2>',
    'desc-icon1' => '<p>Elaboração de balancetes, balanços e DREs com análise estratégica dos indicadores contábeis.</p>',
    'desc-icon2' => '<p>Planejamento tributário criativo e eficaz, visando a maximização de benefícios fiscais e a redução da carga tributária.</p>',
    'desc-icon3' => '<p>Controle das obrigações fiscais e acessórias, além da recuperação de créditos e correta classificação fiscal (NCM).</p>',
    'desc-icon4' => '<p>Revisão e análise de enquadramento tributário: Simples Nacional, Lucro Presumido ou Lucro Real, com foco em economia e segurança.</p>',
],
'pessoa-fisica' => [
    'name' => 'pessoa-fisica',
    'title' => 'Pessoa Física',
    'title2' => '<h2>Serviços para Pessoa Física: Assessoria Personalizada e Eficiente</h2>',
    'desc' => '<p>Atendemos pessoas físicas com soluções completas para suas obrigações fiscais, planejamento financeiro, regularização junto aos órgãos públicos e muito mais. Nosso objetivo é simplificar a sua vida financeira e garantir conformidade com a legislação vigente.</p>',
    'icon1' => '<i class="fa-solid fa-receipt"></i>',
    'icon2' => '<i class="fa-solid fa-id-card"></i>',
    'icon3' => '<i class="fa-solid fa-piggy-bank"></i>',
    'icon4' => '<i class="fa-solid fa-house-circle-check"></i>',
    'icon-title1' => '<h2>Imposto de Renda</h2>',
    'icon-title2' => '<h2>Regularização de CPF</h2>',
    'icon-title3' => '<h2>Planejamento Pessoal</h2>',
    'icon-title4' => '<h2>Transações Patrimoniais</h2>',
    'desc-icon1' => '<p>Preparamos sua declaração de IR com precisão, maximizando suas restituições e evitando pendências com o Fisco.</p>',
    'desc-icon2' => '<p>Auxiliamos na resolução de problemas com CPF, como pendências ou bloqueios, de forma rápida e segura.</p>',
    'desc-icon3' => '<p>Oferecemos estratégias para gestão financeira e tributária pessoal, garantindo tranquilidade e economia a longo prazo.</p>',
    'desc-icon4' => '<p>Consultoria para aquisição, venda ou doação de bens, com suporte jurídico e contábil para segurança e economia.</p>',
],
      
    ]
?>